name: Update readme ⭐️ progress

on:
    schedule:
        - cron: "51 */4 * * *" # Every 4 hours
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: k2bd/advent-readme-stars@v1
              userId: ${{ secrets.AOC_USER_ID }}
              sessionCookie: ${{ secrets.AOC_SESSION }}
              year: 2022
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "update readme progess"
